apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d17ojmcxl-nodejs 
  janus-idp.io/tekton: d17ojmcxl-nodejs
  backstage.io/kubernetes-id: d17ojmcxl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d17ojmcxl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml